service: api-gateway-plant

frameworkVersion: '2'

functions:
  hello:
    handler: handler.hello
    events: 
      - http:
          path: saludos/{name}
          method: get
  addMeasurement:
    handler: handler.addMeasurement
    events:
      - http:
          path: mreasurement/add
          method: post
  getAllMeasurement:
    handler: handler.getAllMeasurement
    events:
      - http:
          path: measurement/all
          method: get

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: measurementTable
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DynamoDbTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:Scan
                - dynamodb:UpdateItem
              Resource: arn:aws:dynamodb:*:*:table/personsTable
        Roles:
          - Ref: IamRoleLambdaExecution
